### ISSUE TITLE
Another white page issue

### ISSUE THREAD

**Issue by keithy999** [grafolean/grafolean#24] opened 2021-06-20 13:04 UTC
Getting another completely white page when editing 'total traffic on entity' widget.

Logs below

[192.168.88.142-1624194105166.log](https://github.com/grafolean/grafolean/files/6682370/192.168.88.142-1624194105166.log)
[192.168.88.142-1624194098854.log](https://github.com/grafolean/grafolean/files/6682371/192.168.88.142-1624194098854.log)
[192.168.88.142-1624194090934.log](https://github.com/grafolean/grafolean/files/6682372/192.168.88.142-1624194090934.log)
[192.168.88.142-1624194085437.log](https://github.com/grafolean/grafolean/files/6682373/192.168.88.142-1624194085437.log)
 
Thanks

**Comment by grafolean** [comment] 2021-06-20 13:47
Hey, thanks for reporting! 

Am I correct in assuming that the data still isn't showing? I will fix the error so that it doesn't crash the frontend (this should never happen anyway), but I think the core problem is that your system is not receiving any NetFlow data from the NetFlow bot, or the NetFlow bot is not receiving any data from your MikroTik router yet.

You can check what is happening by tailing the NetFlow bot logs:

```
$ docker logs -f grafolean-netflow-bot
```

If everything is setup correctly (your router was added to Grafolean as entity and netflow protocol was enabled on it), then you should see:
```
INF | Sending results to Grafolean
INF | Results sent: [{...}]
```

If this is not happening, please make sure you have followed the step 2 in this guide: https://github.com/grafolean/grafolean/blob/master/doc/HOWTO-NetFlow.md

If something is not clear just let me know, I'd be happy to help and fix the docs where needed.

In the mean time I'll fix the white page, as it is not very informative. :)

**Comment by keithy999** [comment] 2021-06-20 14:00
No, data is flowing fine and showing up in the dashboard :)

Its just these white pages

also, I've noticed another console error. This is on the main dashboard page when its showing data. I've no idea whether this is important or useful but here it is anyway

HTH and thanks again!

![gr](https://user-images.githubusercontent.com/16356967/122676992-41ae1180-d1d8-11eb-9887-0f4e92fddac1.png)

**Comment by grafolean** [comment] 2021-06-20 14:27
Huh, interesting... Thank you for clarifying. I can't reproduce this with data flowing in, but I will add some safeguards and better reporting (plus fix the bugs I can reproduce, which might solve others too). Also thank you for the screenshot - it looks like some entities might not be accessible which should never happen.

Btw, you might want to remove the screenshot (or edit out the IPs) if any of them are yours... if you care about that. :)

Since I don't see these errors in my production system, I assume that there is some single root cause for them. It might take a day or two for the fix(es) to land though, I hope this is soon enough... IIUC the core functionality (looking at and investigating the data) works as it should?

Thanks again for reporting this, I will try to fix it asap.

**Comment by grafolean** [comment] 2021-06-29 19:36
Again, thanks for noticing and for taking the time to report this!

This issue has only affected new installations so it went undetected for a

**Comment by grafolean** [comment] 2021-07-02 16:14
Closing this issue, feel free to reopen or start another one if you encounter any further difficulties.

**Closed by grafolean** 2021-07-02 16:14 UTC
