### ISSUE TITLE
Error on creating first user; no config options on login

### ISSUE THREAD

**Issue by dalbrightgit** [grafolean/grafolean#15] opened 2021-02-25 16:59 UTC
Sorry, new issue with me creating a first user.   

I got the web server up and it asks me to create a user.  I enter the information and it returns an error.   
<img width="303" alt="Screen Shot 2021-02-25 at 10 52 55 AM" src="https://user-images.githubusercontent.com/79554063/109188745-d8058580-7758-11eb-813e-a8d9cdc06680.png">

If I refresh the browser, it DOES ask me to login and I am able to, BUT the options are very limited in terms of what I can do.  I do not see any options for Dashboards, Managed entities, etc.   
<img width="1258" alt="Screen Shot 2021-02-25 at 10 56 03 AM" src="https://user-images.githubusercontent.com/79554063/109188260-5b72a700-7758-11eb-9fee-2d79cf97bfe6.png">

docker-compose logs -f on grafolean for this time period show: 
<img width="1832" alt="Screen Shot 2021-02-25 at 10 52 30 AM" src="https://user-images.githubusercontent.com/79554063/109188324-704f3a80-7758-11eb-8f1d-31e101194462.png">

Sorry I keep troubling you - Appreciate all of the help!

**Comment by grafolean** [comment] 2021-02-25 18:24
No problem at all, thank you for reporting this, and especially thank you for the detailed report! It helps a lot.

The problem is already the first error. The returned 502 response indicates that the system wasn't prepared as it should have been - account and the associated bots were not created, which resulted in an empty app. 

The challenge is, however, that there is nothing in the logs to indicate *why* the gunicorn worker would not respond in time. Since other things seem to work and since the user itself apparently *was* created, I am assuming the worker just ran out of time before it got killed. 

I have now prepared a version `v0.4.19-rc.16` which changes the timeout to a much longer period (10 min instead of 30 s). To use it, you should change the version in `docker-compose.yml` like this:
```
  grafolean:
    # If you wish to load an explicit version, change the next line. For example:
    #   image: grafolean/grafolean:v1.0.0
    image: grafolean/grafolean:v0.4.19-rc.16
```

Two notes:
- the version will be available in about half an hour from now (it takes forever to build with QEMU for some reason)
- unfortunately, there is no easy way to fix the database - the first user configuration process failed somewhere in the middle. Can you maybe remove the database directory and try again?

Note that I am guessing a bit here what the reason could be, because the logs don't actually indicate the cause for the error, apart from timeout. Hopefully this should fix it, otherwise I need to find a way to replicate this. Are you at liberty to share the version and amount of memory of your Raspberry Pi?

**Comment by dalbrightgit** [comment] 2021-02-25 18:36
Your support is amazing!  
I have become an expert at deleting the db ;)   I am learning so much on this fun little project.  I'll wait a little while and rebuild on rc.16.  

The pi I am using is a brand-new Raspberry Pi 4 Model B Rev 1.2 with 4GB.  I am happy to send more logs if you need them.

**Comment by dalbrightgit** [comment] 2021-02-25 19:43
IT WORKED! 
thanks so much!

**Comment by dalbrightgit** [comment] 2021-02-25 21:09
me again!  I got snmp monitoring working (yay), but Grafolean does not seem to be receiving any of the NetFlow packets being send by my router.   I ran tcpdump port 2055 on the Pi, and do see packets arriving at 2055.   I cannot figure out how to get the logs for just NetFlow 

Thanks!

**Comment by dalbrightgit** [comment] 2021-02-25 21:16
Found the collector logs, and I see an "Address already in use" error but not sure what the means

![Untitled](https://user-images.githubusercontent.com/79554063/109218644-5d4e6180-777c-11eb-84c5-669435537082.jpg)

**Comment by grafolean** [comment] 2021-02-26 04:48
Hi, glad you made it work so far! :)

"Address already in use" means that something else is already listening on this port. You can check with:
```
$ sudo netstat -upln
```

Then just stop whatever it is and restart Grafolean. Alternatively, you can also setup NetFlow collector to listen to another port (edit `docker-compose.yml` and change `NETFLOW_PORT` to some other value), but you probably don't want to have two NetFlow collectors running anyway. :)

**Comment by dalbrightgit** [comment] 2021-02-26 18:12
Thank you!  I am 100% up and running now :)

**Comment by grafolean** [comment] 2021-02-28 09:24
Nice to hear that! At least now you know 100% where the data is, having had to erase it so many times... ;-) 

Closing this issue as solved, but feel free open another one if something else comes up. Enjoy!

**Closed by grafolean** 2021-02-28 09:24 UTC
