### ISSUE TITLE
ERROR: for grafolean-netflow-collector  "host" network_mode is incompatible with port_bindings

### ISSUE THREAD

**Issue by online-stuff** [grafolean/grafolean#12] opened 2021-01-14 21:53 UTC
I've done this a couple of times now and I get stuck at the same spot each time..  Same error..

`~ $ docker-compose up -d`

```
grafolean-autoheal is up-to-date
grafolean-ping-bot is up-to-date
postgres is up-to-date
mosquitto is up-to-date
grafolean is up-to-date
grafolean-snmp-bot is up-to-date
grafolean-netflow-bot is up-to-date
Creating grafolean-netflow-collector ...
grafolean-netflow-writer is up-to-date

ERROR: for grafolean-netflow-collector  "host" network_mode is incompatible with port_bindings

ERROR: for netflowcollector  "host" network_mode is incompatible with port_bindings

```

`docker.errors.InvalidArgument: "host" network_mode is incompatible with port_bindings
`

I do not do much with Docker..  I apologize if there is a simple fix, but web searches are coming up empty.

**Comment by grafolean** [comment] 2021-01-15 06:59
Interesting... for me it works, and my web searches also turn out empty.

Would you mind sharing the `docker` and `docker-compose` versions? Maybe I can reproduce locally... For reference, these versions are known to work:
```
$ docker --version 
Docker version 18.09.7, build 2d0083d
$ docker-compose --version
docker-compose version 1.23.2, build 1110ad0
```

If I were to guess however, it is possible that newer Docker versions do not allow `ports` with `network_mode: "host"`. Can you maybe remove these two lines from `docker-compose.yml` and try again?
```
    ports:
      - "${NETFLOW_PORT:-2055}:2055/udp"
```

**Comment by online-stuff** [comment] 2021-01-15 22:10
Docker version 20.10.2, build 2291f61
docker-compose version 1.27.4, build unknown

Removing those two lines, it starts successfully.  But it will not open in a browser..  According to Telnet, the port isn't open.

**Comment by grafolean** [comment] 2021-01-17 10:37
Are you on Linux or some other OS? The reason I am asking is that I have installed the exact same versions on a test (Linux) machine now and it started without a problem for me (no error because of the two lines, and port 80 is also accessible). 

About port 80, if you are on Linux, this command should show you if Grafolean is listening on correct port:
```
# netstat -tpln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      19822/docker-proxy  
...
```

Is it possible that you have some firewall which doesn't allow inbound connections to port 80?

Please note: in the process of testing I have also noticed that TimescaleDB released an upgraded (breaking) version, which means that Grafolean had trouble initializing the database (at a later step). The new `docker-compose.yml` now pins the version to `1.7.4` to avoid this issue. You should re-download `docker-compose.yml`  to avoid this problem (step 1 in [installation instructions](https://github.com/grafolean/grafolean#installation)) - sorry about that.

**Comment by online-stuff** [comment] 2021-01-17 23:40
Yes Linux,

` $ sudo netstat -tpln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      476/sshd
tcp6       0      0 :::22                   :::*                    LISTEN      476/sshd
`

` $ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination

Chain FORWARD (policy DROP)
target     prot opt source               destination
DOCKER-USER  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-1  all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere             ctstate RELATED,ESTABLISHED
DOCKER     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere
ACCEPT     all  --  anywhere             anywhere

Chain OUTPUT (policy ACCEPT)
target     prot opt source               destination

Chain DOCKER (2 references)
target     prot opt source               destination

Chain DOCKER-ISOLATION-STAGE-1 (1 references)
target     prot opt source               destination
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
DOCKER-ISOLATION-STAGE-2  all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-ISOLATION-STAGE-2 (2 references)
target     prot opt source               destination
DROP       all  --  anywhere             anywhere
DROP       all  --  anywhere             anywhere
RETURN     all  --  anywhere             anywhere

Chain DOCKER-USER (1 references)
target     prot opt source               destination
RETURN     all  --  anywhere             anywhere
`

**Comment by grafolean** [comment] 2021-01-18 07:14
Thank you for the detailed report, I think we are almost there!

Is it possible that you missed step 3 of [installation process](https://github.com/grafolean/grafolean#installation)? In particular, did you set the `EXTERNAL_HOSTNAME` environment variable?

Grafolean refuses to start if this variable is not set, because it is essential for correct functioning (we have Content Security Policy in place for better security, and we need this information from the start). 

You can confirm this error by looking at the logs:
```
$ sudo docker-compose logs grafolean
...
grafolean           | WARNING: MQTT_WS_HOSTNAME is not set, consequently Content-Security-Policy headers will disallow websockets connection.
grafolean           | To avoid further problems, exiting now with error.
grafolean           |  - if you are using default Docker installation: set this to the domain or IP under which this container will be accessible
grafolean           |  - otherwise: set this to the domain or IP under which the MQTT broker's websocket service will be accessible, and don't
grafolean           |    forget to set MQTT_WS_PORT too (unless it is the same as the port of backend - 80 or 443)
grafolean           | 2021-01-18 06:52:10,943 INFO exited: bootstrap (exit status 1; not expected)
grafolean           | 2021-01-18 06:52:11,944 INFO gave up: bootstrap entered FATAL state, too many start retries too quickly
```

(`EXTERNAL_HOSTNAME` gets translated internally to `MQTT_WS_HOSTNAME` - I ~~will make~~ have now made the error message clearer and more prominent in v0.4.18)

**Comment by online-stuff** [comment] 2021-01-18 07:56
I used vi/vim rather than nano, but yes, I set the EXTERNAL_HOSTNAME.  I have not set " DB admin credentials" from the same section without first figuring out where the 'other side' was to match, and it says optional.  Plus troubleshooting, KISS principle.. :)

**Comment by grafolean** [comment] 2021-01-18 09:15
True, I agree with the approach completely - though if you want to run something in production, it is easier to change the credentials at the beginning than later. :-)

> exec user process caused: exec format error

Aha, now we know the reason... Which architecture (CPU) are you on?

```
$ uname -i
x86_64
```

Grafolean is currently only available on `x86` - there is no special reason for it, I just never set it up to compile for different targets because nobody needed it before. If you post the output of `uname -i` I can try to set it up for your architecture too.

Sidenote: [SNMP bot](https://github.com/grafolean/grafolean-snmp-bot) is available for x86 (`amd64`), `arm/v7` and `arm64`, so if you have one of those, it should already be running without this error:
```
$ docker-compose logs snmpbot
```

**Comment by online-stuff** [comment] 2021-01-19 06:05
> Aha, now we know the reason... Which architecture (CPU) are you on?

```
~ $ uname -i
unknown

```

armv7 - Raspberry Pi 3

```
~ $ uname -a
Linux raspberrypi 5.4.83-v7+ #1379 SMP Mon Dec 14 13:08:57 GMT 2020 armv7l GNU/Linux

```

`$ docker-compose logs snmpbot`

Produced a very long error output..

```
~ $ docker-compose logs snmpbot
Attaching to grafolean-snmp-bot
grafolean-snmp-bot  | Traceback (most recent call last):
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
grafolean-snmp-bot  |     "__main__", mod_spec)
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
grafolean-snmp-bot  |     exec(code, run_globals)
grafolean-snmp-bot  |   File "./snmpbot.py", line 14, in <module>
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
grafolean-snmp-bot  |     from psycopg2._psycopg import (                     # noqa
grafolean-snmp-bot  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
grafolean-snmp-bot  | Traceback (most recent call last):
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
grafolean-snmp-bot  |     "__main__", mod_spec)
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
grafolean-snmp-bot  |     exec(code, run_globals)
grafolean-snmp-bot  |   File "./snmpbot.py", line 14, in <module>
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
grafolean-snmp-bot  |     from psycopg2._psycopg import (                     # noqa
grafolean-snmp-bot  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
grafolean-snmp-bot  | Traceback (most recent call last):
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
grafolean-snmp-bot  |     "__main__", mod_spec)
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
grafolean-snmp-bot  |     exec(code, run_globals)
grafolean-snmp-bot  |   File "./snmpbot.py", line 14, in <module>
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 51, in <module>
grafolean-snmp-bot  |     from psycopg2._psycopg import (                     # noqa
grafolean-snmp-bot  | ImportError: libpq.so.5: cannot open shared object file: No such file or directory
grafolean-snmp-bot  | Traceback (most recent call last):
grafolean-snmp-bot  |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
grafolean-snmp-bot  |     "__main__", mod_spec)

```


Except 30,000+ lines of it..

**Comment by grafolean** [comment] 2021-01-19 17:52
I have never tried running Grafolean on RaspberryPi because it needs to write data somewhere and SD cards are... not known for their longevity, to put it mildly.

I do have just a SNMP bot running on a read-only file system (see [here](https://grafolean.medium.com/run-docker-on-your-raspberry-pi-read-only-file-system-raspbian-1360cf94bace) for more info) and reporting data to https://app.grafolean.com/ and this seems to work very reliably.

Still, sounds like a fun idea... :slightly_smiling_face: I am working now on making a build for RPi, though the build process using qemu is very slow (15 minutes before it fails :roll_eyes:). Will post here how it goes.

**Comment by online-stuff** [comment] 2021-01-19 18:54
> I have never tried running Grafolean on RaspberryPi because it needs to write data somewhere and SD cards are... not known for their longevity, to put it mildly.

I agree with you about the SD cards but I buy good SD cards for a reason..  :)  Cheap SSDs aren't known for longevity either, but some are..  ;)

I apologize, Docker is interesting to say the least but I have not spent a lot of time on it.  I thought was mostly cross-platform, except for some unique cases..

**Comment by grafolean** [comment] 2021-01-21 21:09
Ok, so this was a bit bigger project than I thought it would be... :) Good news is, I managed to build everything for `armv7` and succesfully ran it on RaspberryPi 4. I have used a read-only filesystem with database mounted to `tmpfs` though - I lost too many good SD cards to power outages. ;)

It will take some time for the changes to be incorporated to the main branch, mainly because the build times are quite a bit longer (for SNMP bot using qemu for 3 architectures increases build time from <2 minutes to 40-50 minutes). I also need to double check all the changes and docker image sizes before merging them to the main branch. There should be no changes that affect reliability of the app though.

Anyway, to run Grafolean on RaspberryPi, only the first installation step is a bit different:
```
$ curl https://raw.githubusercontent.com/grafolean/grafolean/feature/multi-arch/install/docker-compose.yml > docker-compose.yml
```

Everything else is the same. The changed `docker-compose.yml` will fetch the pinned versions of all the services, which should all have the necessary modifications needed to run on RaspberryPi.

> I apologize, Docker is interesting to say the least but I have not spent a lot of time on it. I thought was mostly cross-platform, except for some unique cases.

No worries, I needed an excuse to build it for Raspberry Pi anyway. And the project doesn't state it is x86-only. ;) Otherwise Docker (and containers in general) is a fascinating piece of technology and well worth investigating. Basically Docker containers are just processes with their own filesystem and with limited access rights to the syscalls, so they are unfortunately not architecture agnostic.

Anyway, let me know how it goes! And if the SD card survives for a few months, please do share the tips on where to find such resilient cards... ;)

**Comment by online-stuff** [comment] 2021-01-23 09:36
Progress...  I rebuilt the system from scratch..  Just changing the docker-compose file gave me 60 second HTTP timeout errors..  Verbose logs didn't indicate it was actually trying to pull anything though..

After re-imaging and system it at least starts..

After fumbling around, I got Netflow setup, but it doesn't work..
`
docker-compose logs
`

```
grafolean           | 2021-01-23 09:26:54 | INF | Connecting to database, host: [db], db: [grafolean], user: [admin]
grafolean           | 172.18.0.5 - - [23/Jan/2021:09:26:54 +0000] "GET /api/accounts/?b=47920da6-e89e-442b-a46e-cccf407b9195 HTTP/1.1" 200 56 "-" "python-requests/2.22.0" rt=0.056 urt=0.056
grafolean           | 172.18.0.2 - - [23/Jan/2021:09:26:54 +0000] "POST /api/admin/mqtt-auth-plug/aclcheck HTTP/1.1" 200 1 "-" "Go-http-client/1.1" rt=0.050 urt=0.050
grafolean           | 172.18.0.2 - - [23/Jan/2021:09:26:55 +0000] "POST /api/admin/mqtt-auth-plug/aclcheck HTTP/1.1" 200 1 "-" "Go-http-client/1.1" rt=0.011 urt=0.011
grafolean           | 172.18.0.2 - - [23/Jan/2021:09:26:55 +0000] "POST /api/admin/mqtt-auth-plug/aclcheck HTTP/1.1" 200 1 "-" "Go-http-client/1.1" rt=0.010 urt=0.010
grafolean           | 172.18.0.2 - - [23/Jan/2021:09:26:55 +0000] "POST /api/admin/mqtt-auth-plug/aclcheck HTTP/1.1" 200 1 "-" "Go-http-client/1.1" rt=0.010 urt=0.010
grafolean           | 2021-01-23 09:26:55 | ERR | generator didn't stop after throw()
grafolean           | Traceback (most recent call last):
grafolean           |   File "./dbutils.py", line 40, in get_db_connection
grafolean           |   File "./dbutils.py", line 58, in get_db_cursor
grafolean           |   File "./datatypes.py", line 1466, in get_list
grafolean           |   File "./dbutils.py", line 70, in __getattr__
grafolean           | dbutils.DBConnectionError
grafolean           |
grafolean           | During handling of the above exception, another exception occurred:
grafolean           |
grafolean           | Traceback (most recent call last):
grafolean           |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
grafolean           |     rv = self.dispatch_request()
grafolean           |   File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
grafolean           |     return self.view_functions[rule.endpoint](**req.view_args)
grafolean           |   File "./api/accounts.py", line 303, in account_entities
grafolean           |   File "./datatypes.py", line 1487, in get_list
grafolean           |   File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
grafolean           |     self.gen.throw(type, value, traceback)
grafolean           |   File "./dbutils.py", line 61, in get_db_cursor
grafolean           |   File "/usr/local/lib/python3.6/contextlib.py", line 126, in __exit__
grafolean           |     raise RuntimeError("generator didn't stop after throw()")
grafolean           | RuntimeError: generator didn't stop after throw()
grafolean           | 172.18.0.5 - - [23/Jan/2021:09:26:55 +0000] "GET /api/accounts/1899529020/entities/?b=47920da6-e89e-442b-a46e-cccf407b9195 HTTP/1.1" 500 55 "-" "python-requests/2.22.0" rt=0.080 urt=0.080

```

Around 3/4 of the time Monitored Entities gives me " Error fetching entities"

The NetFlow Dashboard says "...waiting for navigation..."

At this point in time RouterOS has sent ~32MB of data, Netflow is around 240 kbps..

**Comment by grafolean** [comment] 2021-01-23 11:12
>... Just changing the docker-compose file gave me 60 second HTTP timeout errors.. Verbose logs didn't indicate it was actually trying to pull anything though..

That... shouldn't happen. If you do `docker-compose pull`, it should pull the correct docker images (for your architecure) from the docker hub. The only thing I can think of is network problems. Can you reach docker hub from command line? (`curl https://hub.docker.com/u/grafolean`)

I have now re-checked everything with fresh Docker (on RPi 4) and pulling the images works, as does running them - I encountered no problem whatsoever. Can you post the procedure an error message, maybe I can help?

> grafolean           | Traceback (most recent call last):
> grafolean           |   File "./dbutils.py", line 40, in get_db_connection
> grafolean           |   File "./dbutils.py", line 58, in get_db_cursor
> grafolean           |   File "./datatypes.py", line 1466, in get_list
> grafolean           |   File "./dbutils.py", line 70, in __getattr__
> grafolean           | dbutils.DBConnectionError

It looks like database is not reachable from `grafolean` container. However `docker-compose-yml` should make sure they are running in the same network, so I assume that it is not running (correctly). Does `docker-compose logs db` show any errors?

> Looking at #5 if it still matters, yes, IPv6 is enabled on my router, and no it isn't possible to disable for testing.

It should be fixed, and I would be very grateful for a confirmation that it works somewhere else than in my test setup. :)

**Comment by grafolean** [comment] 2021-01-23 11:33
What you can also do if you want to debug, is try to run each of the services sparately, one by one, and check if they are running correctly before moving to the next:

```
$ docker-compose up -d db
$ docker-compose logs -f db
... (check that there are no errors)
$ docker-compose up -d mosquitto
$ docker-compose logs -f mosquitto
... (check that there are no errors)
$ docker-compose up -d grafolean
$ docker-compose logs -f grafolean
... (check that there are no errors)
```

At this point you should be able to access the frontend (http://<your-ip>/). Then you simply continue starting other services the same way.

**Comment by online-stuff** [comment] 2021-01-23 12:15
> I have now re-checked everything with fresh Docker (on RPi 4) and pulling the images works, as does running them - I encountered no problem whatsoever. Can you post the procedure an error message, maybe I can help?

I re-imaged it, reinstalled Docker, and it starts now..  Otherwise yes, everything else network wise was working..


> > Looking at #5 if it still matters, yes, IPv6 is enabled on my router, and no it isn't possible to disable for testing.
> 
> It should be fixed, and I would be very grateful for a confirmation that it works somewhere else than in my test setup. :)

Alright, I installed a bare-metal amd64 machine and it works as documented, just borrowed the IP from my Pi board to keep things easy and the same.  haha

**Comment by online-stuff** [comment] 2021-01-23 12:23
> At this point you should be able to access the frontend (http:///). Then you simply continue starting other services the same way.

And now everything appears to work..  :)

I'll let it run for a couple days and see what happens.

**Comment by grafolean** [comment] 2021-01-23 15:25
> I re-imaged it, reinstalled Docker, and it starts now.. Otherwise yes, everything else network wise was working..
> ...
> Alright, I installed a bare-metal amd64 machine and it works as documented

Curious: did you manage to make it work on RPi too before moving to amd64?

Anyway, glad to hear it works, let me know if you stumble across any problems or if you feel that anything is missing wrt. NetFlow monitoring.

And thank you for reporting and debugging the issue(s), it will make things easier for future users.

**Comment by online-stuff** [comment] 2021-01-23 21:42
> Curious: did you manage to make it work on RPi too before moving to amd64?

No..  I re-imaged the Pi 3, using the 2021-01 image rather than the 2020-12 that I had been before.  Just realized now that I used a different version, shouldn't make a difference, but it is a change, I reinstalled Docker and everything, the interface worked, but no data and was giving me the errors as I pasted.

I shutdown the Pi and installed the amd64 system, used the same static IP on the amd64 system that the Pi was using so Netflow and DNS was already setup..  The amd64 system worked flawlessly..

After a few hours I shutdown the amd64 system and rebooted my Pi3..  Everything was working..  Frustrating for issue tracking, but it has been working since.  (Yes I had tried rebooting Raspbian before).



> Anyway, glad to hear it works, let me know if you stumble across any problems or if you feel that anything is missing wrt. NetFlow monitoring.

This might be a noob question but how do I identify interfaces that Grafolean reports?  interface0 to interface 12 *should* be the port number plus 1 (I think interface0 is actually interface1) but interface23 and interface34 mean nothing to me...

As I try and login to confirm the interface numbers it provides, I can't login..  Enter my username and password ` Error: Error 500 - INTERNAL SERVER ERROR` below the Login button, above the Forgot Password.

**Comment by grafolean** [comment] 2021-01-24 12:25
Thank you for the explanation! It is great to get feedback as it helps me identify parts which might not be 100% reliable yet.

> This might be a noob question but how do I identify interfaces that Grafolean reports? interface0 to interface 12 should be the port number plus 1 (I think interface0 is actually interface1) but interface23 and interface34 mean nothing to me...

Not a noob question at all, thank you for bringing it to my attention. I'll update the documentation.

NetFlow protocol doesn't provide nice names for the ports, but SNMP does. If you have an option to enable SNMP on the router you could make Grafolean display nice names (in NetFlow dashboard too!) just by setting up SNMP:

1) enable SNMP on router and note down the credentials (all versions are supported - SNMP v1, v2 and v3)
2) in Grafolean menu choose Credentials -> Add credentials and enter the router SNMP credentials
3) go to Monitored entities, click on the name of your NetFlow exporter, click on Settings; then for SNMP protocol, choose the newly added credentials and enable some of the sensors (Traffic IN/OUT) (it might work if you do not enable any, not 100% sure... would have to check) and click Submit

When SNMP is enabled on device, apart from the selected sensors, Grafolean will also automatically collect network interface names every 5 minutes (the reasoning being that this is so common request that it is not worth having a separate setting for it). Once available, the interface names should automatically be displayed in the NetFlow dashboard.

> As I try and login to confirm the interface numbers it provides, I can't login.. Enter my username and password Error: Error 500 - INTERNAL SERVER ERROR below the Login button, above the Forgot Password.
>
>After coming back after a few hours, I just get a spinning circle instead of the user/pass page.
> Trying to connect to backend at: /api

Something must have gone wrong on the backend... This is Raspberry Pi now if I understand correctly? Could you maybe check the logs again and post the errors from there?

I'm sorry that you are encountering so many problems and I understand if at some point you choose not to continue... :-/ The x86 path is well explored, but the RPi is uncharted waters. Still, as long as you are willing to sail these waters, I am happy to help you navigate and to improve the ship if needed... ;)

**Closed** 2021-02-25 15:12 UTC

**Comment by grafolean** [comment] 2021-02-25 15:13
Closing this issue as it seems to be solved, but feel free to comment (or open a new one) if it is not, and we can solve it then.
